# Generated by Django 4.0 on 2022-05-17 18:34

import apps.common.utils
from django.db import migrations, models
import apps.orders.paths


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitempaper",
            name="paper",
            field=models.FileField(
                max_length=300,
                upload_to=apps.orders.paths.path_order_item_paper,
                validators=[
                    apps.common.utils.FileValidator(
                        content_types=(
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-powerpoint",
                            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sh",
                            "application/zip",
                            "image/jpeg",
                            "image/png",
                            "text/plain",
                        )
                    )
                ],
            ),
        ),
    ]
