# Generated by Django 4.0 on 2022-05-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitempaper_paper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-created_at',)},
        ),
    ]
