# Generated by Django 4.0 on 2022-01-21 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
