default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ['--django']
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-iii', '-ll']

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-mutable',
            'flake8-print',
            'flake8-simplify',
          ]

  - repo: local
    hooks:
      - id: pylint
        exclude: '[a-zA-Z]*/(migrations)/(.)*|[a-zA-Z]*/admin.py|[a-zA-Z]*/apps.py|[a-zA-Z]*/*conftest.py'
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            '--load-plugins=pylint_django',
            '--django-settings-module=nero.settings',
            '--rcfile=.pylintrc',
            '-rn', # Only display messages
            '-sn', # Don't display the score
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
        exclude: '[a-zA-Z]*/(migrations)/(.)*|[a-zA-Z]*/admin.py|[a-zA-Z]*/apps.py'
        additional_dependencies: [
            # mypy dependencies
            djangorestframework-stubs,
            django-stubs,
            # runtime dependencies
            django_tenants,
            python-decouple,
            psycopg2-binary,
            boto3,
            django-storages,
            djangorestframework,
            django-filter,
            python-keycloak,
            celery,
            python-magic,
            django-cors-headers,
            djangorestframework-simplejwt,
            "africastalking",
          ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: '[a-zA-Z]*/(migrations)/(.)*'

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: '[a-zA-Z]*/(migrations)/(.)*'
