[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_first_party = ["tenants"]
known_third_party = ["africastalking", "boto3", "botocore", "celery", "corsheaders", "dateutil", "decouple", "django", "django_filters", "django_tenants", "keycloak", "magic", "paypalrestsdk", "pytest", "pytz", "requests", "responses", "rest_framework", "rest_framework_simplejwt", "six", "storages"]
