# Generated by Django 4.0 on 2022-02-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
    ]
