# Generated by Django 4.0 on 2022-01-10 08:01

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('site_url', models.CharField(blank=True, max_length=60, null=True)),
                ('default_from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('frontend_email_verify_url', models.CharField(blank=True, max_length=255, null=True)),
                ('frontend_email_password_reset_url', models.CharField(blank=True, max_length=255, null=True)),
                ('google_recaptcha_key', models.TextField(blank=True, null=True)),
                ('google_oauth_client_id', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(blank=True, help_text='Primary color for the site e.g #ff0000', max_length=10, null=True)),
                ('secondary_color', models.CharField(blank=True, help_text='Secondary color for the site e.g #000000', max_length=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
