# Generated by Django 4.0 on 2022-06-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_frontend_email_password_reset_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='google_recaptcha_key',
            new_name='google_recaptcha_secret_key',
        ),
    ]
