# Generated by Django 4.0 on 2022-06-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_rename_google_recaptcha_key_tenant_google_recaptcha_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='google_oauth_client_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='google_recaptcha_secret_key',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='site_url',
        ),
    ]
