# Generated by Django 4.0 on 2022-10-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_attachment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tawkto_property_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tawkto_widget_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
