# Generated by Django 4.0 on 2022-12-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_tawkto_property_id_tenant_tawkto_widget_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='default_from_email',
        ),
    ]
