# Generated by Django 4.0 on 2022-12-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='order_sms_recipients',
            field=models.CharField(blank=True, help_text='Phone number of recipients who will receive\n        SMS notifications for new orders separated by commas and starting with 254\n        . e.g 254700000000,254711111111', max_length=255, null=True),
        ),
    ]
