# Generated by Django 4.0 on 2023-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_order_sms_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
