# Generated by Django 4.0 on 2023-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ga_measurement_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
