# Generated by Django 4.0 on 2023-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_ga_measurement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='ga_measurement_id',
            field=models.CharField(blank=True, help_text='Google Analytics Measurement ID', max_length=255, null=True),
        ),
    ]
