# Generated by Django 4.0 on 2023-08-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_enable_client_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='enable_client_login',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
