# Generated by Django 4.0 on 2022-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the name. All lowercase and contains only\n        letters, numbers and hyphens. If not provided, the name will be used as URL', max_length=60, unique=True),
        ),
    ]
