# Generated by Django 4.0 on 2022-10-11 12:25

import apps.blog.utils
import apps.common.backends.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.common.backends.storage.PublicMediaStorage,
                upload_to=apps.blog.utils.image_path,
            ),
        ),
    ]
