# Generated by Django 4.0 on 2022-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_draft_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title. All lowercase and contains only\n        letters, numbers and hyphens. If not provided, the title will be used as URL', max_length=60, unique=True),
        ),
    ]
