# Generated by Django 4.0 on 2022-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentmethod_instructions_alter_paymentmethod_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
