# Generated by Django 4.0 on 2022-12-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_paymentmethod_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('BRAINTREE', 'Braintree'), ('INSTRUCTIONS', 'Instructions'), ('TWOCHECKOUT', '2Checkout')], max_length=20),
        ),
    ]
