# Generated by Django 4.0 on 2022-04-23 13:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name. All lowercase and contains only\n        letters, numbers and hyphens. If not provided, the name will be used as URL', max_length=60)),
                ('seo_title', models.CharField(blank=True, max_length=60, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('navbar_index', models.SmallIntegerField(blank=True, null=True)),
                ('footer_index', models.SmallIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=False)),
                ('blocks', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
