# Generated by Django 4.0 on 2022-04-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='footer_index',
            new_name='footer_sort_order',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='navbar_index',
            new_name='navbar_sort_order',
        ),
    ]
