# Generated by Django 4.0 on 2022-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_footer_index_page_footer_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='landing_page_configs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
