# Generated by Django 4.0 on 2022-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_landing_page_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='draft',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
