# Generated by Django 4.0 on 2022-06-15 08:48

import apps.common.backends.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=10000, storage=apps.common.backends.storage.PublicMediaStorage, upload_to='pages/images/'),
        ),
    ]
