# Generated by Django 4.0 on 2022-07-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='landing_page_configs',
            new_name='landing_page',
        ),
    ]
