# Generated by Django 4.0 on 2022-07-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_navbarlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='link_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar_links', to='pages.page'),
        ),
    ]
