# Generated by Django 4.0 on 2022-07-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_footergroup_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='link_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='pages.page'),
        ),
    ]
