# Generated by Django 4.0 on 2022-07-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_footerlink_link_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarlink',
            options={'ordering': ('created_at',)},
        ),
    ]
