# Generated by Django 4.0 on 2022-07-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_footergroup_options_footergroup_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footergroup',
            options={'ordering': ('sort_order', 'title')},
        ),
    ]
