# Generated by Django 4.0 on 2022-07-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_footergroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='footerlink',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The position of display when ordering is done by this field', null=True),
        ),
    ]
