# Generated by Django 4.0 on 2022-10-21 04:42

import apps.common.backends.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=500, storage=apps.common.backends.storage.PublicMediaStorage, upload_to='pages/images/'),
        ),
    ]
