# Generated by Django 4.0 on 2022-12-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
