# Generated by Django 4.0 on 2023-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
