# Generated by Django 4.0 on 2023-05-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_navbarlink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
