# Generated by Django 4.0 on 2023-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the name. All lowercase and contains only\n        letters, numbers and hyphens. If not provided, the name will be used as URL', max_length=60, unique=True),
        ),
    ]
