# Generated by Django 4.0 on 2023-08-20 08:04

import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_home',
        ),
        migrations.RemoveField(
            model_name='page',
            name='landing_page',
        ),
        migrations.AddField(
            model_name='page',
            name='metadata',
            field=models.JSONField(default=apps.pages.models.default_empty_json),
        ),
    ]
