# Generated by Django 4.0 on 2023-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_page_is_home_remove_page_landing_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='draft',
            field=models.JSONField(default=list),
        ),
    ]
