# Generated by Django 4.0 on 2022-02-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writertypeservice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AddField(
            model_name='writertypeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_prices', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='writertypeservice',
            name='writer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_prices', to='catalog.writertype'),
        ),
        migrations.AddField(
            model_name='writertype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AddField(
            model_name='service',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.deadline'),
        ),
        migrations.AddField(
            model_name='service',
            name='level',
            field=models.ForeignKey(blank=True, help_text='If left none, this service will be given priority and used for all levels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.level'),
        ),
        migrations.AddField(
            model_name='service',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AddField(
            model_name='level',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AddField(
            model_name='format',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='writertypeservice',
            unique_together={('writer_type', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('level', 'deadline', 'paper')},
        ),
        migrations.AlterUniqueTogether(
            name='deadline',
            unique_together={('value', 'deadline_type')},
        ),
    ]
