# Generated by Django 4.0 on 2022-02-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writertype',
            name='is_default',
        ),
    ]
