# Generated by Django 4.0 on 2022-02-02 12:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('coupon_type', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'First timer')], default=1)),
                ('percent', models.PositiveSmallIntegerField(help_text='The discount in percentage this coupon will give')),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount required', max_digits=15, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this coupon will start to take effect')),
                ('end_date', models.DateTimeField(help_text='The date and time this coupon will stop to take effect')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
