# Generated by Django 4.0 on 2023-02-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='percent',
            new_name='percent_off',
        ),
    ]
