# Generated by Django 4.0 on 2023-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_rename_percent_coupon_percent_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'First Timer')], default=1),
        ),
    ]
